<?php

include('backend/db.php');
session_start();

$user = $_SESSION['name'];
$secret = $_SESSION['secret'];
$id = $_SESSION['id'];
require_once 'PHPGangsta/GoogleAuthenticator.php';
$ga = new PHPGangsta_GoogleAuthenticator();
//$qrCodeUrl = $ga->getQRCodeGoogleUrl($user, $secret, "");
//if (empty($secret)){
//    $secret = $ga->createSecret();
//    $sql = "UPDATE `users` SET `Googlecode` = ? WHERE id = ?";
//    $stmt = $mysqli->prepare($sql);
//    $stmt->bind_param(
//        "si",
//        $secret,$id
//    );
//    $stmt->execute();
//}
//$secret = $ga->createSecret();
//echo "$secret";
//$salt = '7WAO342QFANY6IKBF7L7SWEUU79WL3VMT920VB5NQMW';
//$secret = $user.$salt;

//$qrCodeUrl = $ga->getQRCodeGoogleUrl($user, $secret);
//echo "Google Charts URL for the QR-Code: ".$qrCodeUrl."\n\n"


?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Google Two Factor Authentication Login with PHP</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
            integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js"
            integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets2/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets2/css/layout.css">
    <link rel="stylesheet" href="css/form-design.css">
    <link rel="stylesheet" href="assets2/css/font-awesome.min.css">
</head>
<body class="a2z-wrapper">

<!--Start a2z-area-->
<section class="a2z-area mt-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="form-area register-from">
                    <div class="form-content">
                        <h2>Google Two Factor Authentication</h2>
                        <p>Enter the verification code generated by Google Authenticator app on your phone.</p>

                    </div>
                    <div class="form-input">
                        <h2>Enter Code</h2>
                        <form name="reg" action="backend/auth.php" method="POST">

                            <div class="form-group">
                                <img src='<?php
                                if (empty($secret)) {
                                    $secret = $ga->createSecret();
                                    $sql = "UPDATE `users` SET `Googlecode` = ? WHERE id = ?";
                                    $stmt = $mysqli->prepare($sql);
                                    $stmt->bind_param(
                                        "si",
                                        $secret,$id
                                    );
                                    $stmt->execute();
                                    $qrCodeUrl = $ga->getQRCodeGoogleUrl($user, $secret);
                                    echo $qrCodeUrl;
                                }
                                ?>'/>
                            </div>

                            <div class="form-group">
                                <input type="hidden" name="secret" id="secret" value="<?php echo $secret; ?>" required>
                                <input type="text" name="code" id="code" autocomplete="off" value="" required>
                                <label>Enter Google Authenticator Code</label>
                            </div>

                            <div class="a2z-button">
                                <button name="btnValidate" type="submit" class="a2z-btn">Submit</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>